# Generated by Django 4.2.6 on 2023-11-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_faculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
