# Generated by Django 4.2.6 on 2023-11-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('chief_guest', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('venue', models.CharField(max_length=255)),
                ('audience', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
